# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: google/internal/labs/tailwind/orchestration/v1/agency/supported.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'google/internal/labs/tailwind/orchestration/v1/agency/supported.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nEgoogle/internal/labs/tailwind/orchestration/v1/agency/supported.proto\x12\x35google.internal.labs.tailwind.orchestration.v1.agency\"O\n\rTailwindValue\x12\x14\n\x0cnumber_value\x18\x02 \x01(\x01\x12\x14\n\x0cstring_value\x18\x03 \x01(\t\x12\x12\n\nbool_value\x18\x04 \x01(\x08\"w\n\x13TailwindStructEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12S\n\x05value\x18\x02 \x01(\x0b\x32\x44.google.internal.labs.tailwind.orchestration.v1.agency.TailwindValue\"l\n\x0eTailwindStruct\x12Z\n\x06\x66ields\x18\x01 \x03(\x0b\x32J.google.internal.labs.tailwind.orchestration.v1.agency.TailwindStructEntry\" \n\x10\x46unctionResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\"q\n\x0c\x46unctionCall\x12\x0c\n\x04name\x18\x01 \x01(\t\x12S\n\x04\x61rgs\x18\x02 \x01(\x0b\x32\x45.google.internal.labs.tailwind.orchestration.v1.agency.TailwindStructb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.internal.labs.tailwind.orchestration.v1.agency.supported_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TAILWINDVALUE']._serialized_start=128
  _globals['_TAILWINDVALUE']._serialized_end=207
  _globals['_TAILWINDSTRUCTENTRY']._serialized_start=209
  _globals['_TAILWINDSTRUCTENTRY']._serialized_end=328
  _globals['_TAILWINDSTRUCT']._serialized_start=330
  _globals['_TAILWINDSTRUCT']._serialized_end=438
  _globals['_FUNCTIONRESPONSE']._serialized_start=440
  _globals['_FUNCTIONRESPONSE']._serialized_end=472
  _globals['_FUNCTIONCALL']._serialized_start=474
  _globals['_FUNCTIONCALL']._serialized_end=587
# @@protoc_insertion_point(module_scope)
