# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notebooklm/android/wire/v1/b6_sharing.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'notebooklm/android/wire/v1/b6_sharing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+notebooklm/android/wire/v1/b6_sharing.proto\x12\x1anotebooklm.android.wire.v1\"\x0f\n\rEmptyResponse\"N\n\x15ProjectPublicSettings\x12\x1c\n\x14is_publicly_readable\x18\x01 \x01(\x08\x12\x17\n\x0fis_discoverable\x18\x02 \x01(\x08\".\n\x18GetProjectDetailsRequest\x12\x12\n\nproject_id\x18\x01 \x01(\t\"\xf7\x01\n\x19GetProjectDetailsResponse\x12J\n\x0fpublic_settings\x18\x02 \x01(\x0b\x32\x31.notebooklm.android.wire.v1.ProjectPublicSettings\x12(\n\x1bmax_individuals_share_limit\x18\x03 \x01(\x05H\x00\x88\x01\x01\x12&\n\x19is_public_sharing_allowed\x18\x04 \x01(\x08H\x01\x88\x01\x01\x42\x1e\n\x1c_max_individuals_share_limitB\x1c\n\x1a_is_public_sharing_allowed\"c\n*ShareProjectRequest_PublicDocumentSettings\x12\x1c\n\x14is_publicly_readable\x18\x01 \x01(\x08\x12\x17\n\x0fis_discoverable\x18\x02 \x01(\x08\"\xa2\x01\n\"ShareProjectRequest_ProjectToShare\x12\x12\n\nproject_id\x18\x01 \x01(\t\x12h\n\x18public_document_settings\x18\x03 \x01(\x0b\x32\x46.notebooklm.android.wire.v1.ShareProjectRequest_PublicDocumentSettings\"f\n\x13ShareProjectRequest\x12O\n\x07project\x18\x01 \x03(\x0b\x32>.notebooklm.android.wire.v1.ShareProjectRequest_ProjectToShareb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notebooklm.android.wire.v1.b6_sharing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTYRESPONSE']._serialized_start=75
  _globals['_EMPTYRESPONSE']._serialized_end=90
  _globals['_PROJECTPUBLICSETTINGS']._serialized_start=92
  _globals['_PROJECTPUBLICSETTINGS']._serialized_end=170
  _globals['_GETPROJECTDETAILSREQUEST']._serialized_start=172
  _globals['_GETPROJECTDETAILSREQUEST']._serialized_end=218
  _globals['_GETPROJECTDETAILSRESPONSE']._serialized_start=221
  _globals['_GETPROJECTDETAILSRESPONSE']._serialized_end=468
  _globals['_SHAREPROJECTREQUEST_PUBLICDOCUMENTSETTINGS']._serialized_start=470
  _globals['_SHAREPROJECTREQUEST_PUBLICDOCUMENTSETTINGS']._serialized_end=569
  _globals['_SHAREPROJECTREQUEST_PROJECTTOSHARE']._serialized_start=572
  _globals['_SHAREPROJECTREQUEST_PROJECTTOSHARE']._serialized_end=734
  _globals['_SHAREPROJECTREQUEST']._serialized_start=736
  _globals['_SHAREPROJECTREQUEST']._serialized_end=838
# @@protoc_insertion_point(module_scope)
