# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notebooklm/android/wire/v1/organization_mutations.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'notebooklm/android/wire/v1/organization_mutations.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7notebooklm/android/wire/v1/organization_mutations.proto\x12\x1anotebooklm.android.wire.v1\"U\n\x16OrganizationRecordWire\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\nmember_ids\x18\x02 \x03(\x0c\x12\n\n\x02id\x18\x03 \x01(\t\x12\r\n\x05\x65moji\x18\x04 \x01(\t\"\xa4\x01\n\x15GetLabelsWireResponse\x12\x42\n\x06labels\x18\x01 \x03(\x0b\x32\x32.notebooklm.android.wire.v1.OrganizationRecordWire\x12G\n\x0b\x63ollections\x18\x02 \x03(\x0b\x32\x32.notebooklm.android.wire.v1.OrganizationRecordWireb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notebooklm.android.wire.v1.organization_mutations_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORGANIZATIONRECORDWIRE']._serialized_start=87
  _globals['_ORGANIZATIONRECORDWIRE']._serialized_end=172
  _globals['_GETLABELSWIRERESPONSE']._serialized_start=175
  _globals['_GETLABELSWIRERESPONSE']._serialized_end=339
# @@protoc_insertion_point(module_scope)
