"""Web positional-row decoders and typed row views."""

from . import (
    artifacts,
    chat,
    collections,
    customization,
    documents,
    labels,
    notebooks,
    notes,
    research,
    research_task,
    sharing,
    sources,
    transfers,
)
from .artifacts import ArtifactRow, ReportSuggestionRow
from .chat import (
    AnswerRow,
    CitationDetail,
    CitationRow,
    ConversationTurnRow,
    ErrorPayloadRow,
    StreamFrameRow,
    count_question_turn_rows,
    unwrap_conversation_turns,
)
from .collections import CollectionRow
from .customization import (
    CustomizationChoiceRow,
    CustomizationChoicesRow,
    ReportPresetRow,
    unwrap_customization_choices,
)
from .documents import (
    AnnotationEntryRow,
    DocumentBodyRow,
    ParagraphElementRow,
    ParagraphRow,
    StructuralElementRow,
    TextRunRow,
    build_blocks,
    build_document,
)
from .labels import LabelRow
from .notes import NoteRow
from .research import (
    ImportedSourceRow,
    ResearchResultRow,
    ResearchStartRow,
    ResearchTaskInfoRow,
    ResearchTaskRow,
    unwrap_import_rows,
    unwrap_poll_tasks,
)
from .sharing import SharedUserRow, ShareStatusRow
from .sources import SourceRow, SourceRowShape
from .transfers import (
    AddSourcesAsyncResponseRow,
    CopiedArtifactRow,
    CopiedSourceRow,
    SourceAckRow,
    unwrap_mapping_rows,
)

__all__ = [
    "artifacts",
    "chat",
    "collections",
    "customization",
    "documents",
    "labels",
    "notebooks",
    "notes",
    "research",
    "research_task",
    "sharing",
    "sources",
    "transfers",
    "AddSourcesAsyncResponseRow",
    "AnnotationEntryRow",
    "AnswerRow",
    "ArtifactRow",
    "CitationDetail",
    "CitationRow",
    "CollectionRow",
    "ConversationTurnRow",
    "CopiedArtifactRow",
    "CopiedSourceRow",
    "CustomizationChoiceRow",
    "CustomizationChoicesRow",
    "DocumentBodyRow",
    "ErrorPayloadRow",
    "ImportedSourceRow",
    "LabelRow",
    "NoteRow",
    "ParagraphElementRow",
    "ParagraphRow",
    "ReportPresetRow",
    "ReportSuggestionRow",
    "ResearchResultRow",
    "ResearchStartRow",
    "ResearchTaskInfoRow",
    "ResearchTaskRow",
    "SharedUserRow",
    "ShareStatusRow",
    "SourceAckRow",
    "SourceRow",
    "SourceRowShape",
    "StreamFrameRow",
    "StructuralElementRow",
    "TextRunRow",
    "build_blocks",
    "build_document",
    "count_question_turn_rows",
    "unwrap_conversation_turns",
    "unwrap_customization_choices",
    "unwrap_import_rows",
    "unwrap_mapping_rows",
    "unwrap_poll_tasks",
]
