# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: google/internal/labs/tailwind/v1/source_settings.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'google/internal/labs/tailwind/v1/source_settings.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6google/internal/labs/tailwind/v1/source_settings.proto\x12 google.internal.labs.tailwind.v1\"\xab\x01\n\x0eSourceSettings\x12>\n\x06status\x18\x02 \x01(\x0e\x32..google.internal.labs.tailwind.v1.SourceStatus\x12Y\n\x18user_drive_source_status\x18\x04 \x01(\x0e\x32\x37.google.internal.labs.tailwind.v1.UserDriveSourceStatus*\xbe\x01\n\x0cSourceStatus\x12\x1d\n\x19SOURCE_STATUS_UNSPECIFIED\x10\x00\x12\x19\n\x15SOURCE_STATUS_PENDING\x10\x01\x12\x1a\n\x16SOURCE_STATUS_COMPLETE\x10\x02\x12\x17\n\x13SOURCE_STATUS_ERROR\x10\x03\x12\"\n\x1eSOURCE_STATUS_PENDING_DELETION\x10\x04\x12\x1b\n\x17SOURCE_STATUS_TENTATIVE\x10\x05*\xf2\x01\n\x15UserDriveSourceStatus\x12#\n\x1f\x44RIVE_SOURCE_STATUS_UNSPECIFIED\x10\x00\x12$\n DRIVE_SOURCE_STATUS_INACCESSIBLE\x10\x01\x12\x1f\n\x1b\x44RIVE_SOURCE_STATUS_SYNCING\x10\x02\x12\x1e\n\x1a\x44RIVE_SOURCE_STATUS_ACTIVE\x10\x03\x12\x1f\n\x1b\x44RIVE_SOURCE_STATUS_DELETED\x10\x04\x12,\n(DRIVE_SOURCE_STATUS_GEN_AI_ACCESS_DENIED\x10\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.internal.labs.tailwind.v1.source_settings_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SOURCESTATUS']._serialized_start=267
  _globals['_SOURCESTATUS']._serialized_end=457
  _globals['_USERDRIVESOURCESTATUS']._serialized_start=460
  _globals['_USERDRIVESOURCESTATUS']._serialized_end=702
  _globals['_SOURCESETTINGS']._serialized_start=93
  _globals['_SOURCESETTINGS']._serialized_end=264
# @@protoc_insertion_point(module_scope)
