# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: labs/language/tailwind/common/protos/common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'labs/language/tailwind/common/protos/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1labs/language/tailwind/common/protos/common.proto\x12$labs.language.tailwind.common.protos\"&\n\x0b\x43hatSession\x12\x17\n\x0f\x63hat_session_id\x18\x01 \x01(\t\"N\n\x15ProjectPublicSettings\x12\x1c\n\x14is_publicly_readable\x18\x01 \x01(\x08\x12\x17\n\x0fis_discoverable\x18\x02 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'labs.language.tailwind.common.protos.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATSESSION']._serialized_start=91
  _globals['_CHATSESSION']._serialized_end=129
  _globals['_PROJECTPUBLICSETTINGS']._serialized_start=131
  _globals['_PROJECTPUBLICSETTINGS']._serialized_end=209
# @@protoc_insertion_point(module_scope)
