# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: labs/language/tailwind/common/protos/provenance.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'labs/language/tailwind/common/protos/provenance.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5labs/language/tailwind/common/protos/provenance.proto\x12$labs.language.tailwind.common.protos\"\xd5\x02\n\nClientInfo\x12\x62\n\x14\x61pplication_platform\x18\x01 \x01(\x0e\x32\x44.labs.language.tailwind.common.protos.ClientInfo.ApplicationPlatform\x12G\n\x06\x64\x65vice\x18\x02 \x01(\x0e\x32\x37.labs.language.tailwind.common.protos.ClientInfo.Device\x12\x1b\n\x13\x61pplication_version\x18\x03 \x01(\t\"G\n\x13\x41pplicationPlatform\x12$\n APPLICATION_PLATFORM_UNSPECIFIED\x10\x00\x12\n\n\x06NATIVE\x10\x02\"4\n\x06\x44\x65vice\x12\x16\n\x12\x44\x45VICE_UNSPECIFIED\x10\x00\x12\x12\n\x0eMOBILE_ANDROID\x10\x01\"\x85\x02\n\nProvenance\x12_\n\x13origin_product_type\x18\x01 \x01(\x0e\x32\x42.labs.language.tailwind.common.protos.Provenance.OriginProductType\x12\x45\n\x0b\x63lient_info\x18\x0b \x01(\x0b\x32\x30.labs.language.tailwind.common.protos.ClientInfo\"O\n\x11OriginProductType\x12#\n\x1fORIGIN_PRODUCT_TYPE_UNSPECIFIED\x10\x00\x12\x15\n\x11GOOGLE_NOTEBOOKLM\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'labs.language.tailwind.common.protos.provenance_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIENTINFO']._serialized_start=96
  _globals['_CLIENTINFO']._serialized_end=437
  _globals['_CLIENTINFO_APPLICATIONPLATFORM']._serialized_start=312
  _globals['_CLIENTINFO_APPLICATIONPLATFORM']._serialized_end=383
  _globals['_CLIENTINFO_DEVICE']._serialized_start=385
  _globals['_CLIENTINFO_DEVICE']._serialized_end=437
  _globals['_PROVENANCE']._serialized_start=440
  _globals['_PROVENANCE']._serialized_end=701
  _globals['_PROVENANCE_ORIGINPRODUCTTYPE']._serialized_start=622
  _globals['_PROVENANCE_ORIGINPRODUCTTYPE']._serialized_end=701
# @@protoc_insertion_point(module_scope)
