# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notebooklm/android/internal/v1/b4_report_suggestions.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'notebooklm/android/internal/v1/b4_report_suggestions.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n:notebooklm/android/internal/v1/b4_report_suggestions.proto\x12\x1enotebooklm.android.internal.v1\":\n$GenerateReportSuggestionsRequestWire\x12\x12\n\nproject_id\x18\x02 \x01(\t\"b\n\x14ReportSuggestionWire\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0e\n\x06prompt\x18\x05 \x01(\t\x12\x16\n\x0e\x61udience_level\x18\x06 \x01(\x05\"r\n%GenerateReportSuggestionsResponseWire\x12I\n\x0bsuggestions\x18\x01 \x03(\x0b\x32\x34.notebooklm.android.internal.v1.ReportSuggestionWireb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notebooklm.android.internal.v1.b4_report_suggestions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERATEREPORTSUGGESTIONSREQUESTWIRE']._serialized_start=94
  _globals['_GENERATEREPORTSUGGESTIONSREQUESTWIRE']._serialized_end=152
  _globals['_REPORTSUGGESTIONWIRE']._serialized_start=154
  _globals['_REPORTSUGGESTIONWIRE']._serialized_end=252
  _globals['_GENERATEREPORTSUGGESTIONSRESPONSEWIRE']._serialized_start=254
  _globals['_GENERATEREPORTSUGGESTIONSRESPONSEWIRE']._serialized_end=368
# @@protoc_insertion_point(module_scope)
