# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notebooklm/internal/android/wire/v1/artifacts.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'notebooklm/internal/android/wire/v1/artifacts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from notebooklm._android.proto.google.internal.labs.tailwind.orchestration.v1 import chat_pb2 as google_dot_internal_dot_labs_dot_tailwind_dot_orchestration_dot_v1_dot_chat__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3notebooklm/internal/android/wire/v1/artifacts.proto\x12#notebooklm.internal.android.wire.v1\x1a\x39google/internal/labs/tailwind/orchestration/v1/chat.proto\"Y\n\"WireTableArtifactGenerationOptions\x12\x1c\n\x14user_steering_prompt\x18\x01 \x01(\t\x12\x15\n\rlanguage_code\x18\x02 \x01(\t\"\xc7\x01\n\x11WireTableArtifact\x12M\n\x08\x64ocument\x18\x01 \x01(\x0b\x32;.google.internal.labs.tailwind.orchestration.v1.TailwindDoc\x12\x63\n\x12generation_options\x18\x02 \x01(\x0b\x32G.notebooklm.internal.android.wire.v1.WireTableArtifactGenerationOptions\"d\n\x1bWireArtifactTableProjection\x12\x45\n\x05table\x18\x13 \x01(\x0b\x32\x36.notebooklm.internal.android.wire.v1.WireTableArtifact\">\n,WireAudioOverviewGenerationOptionsProjection\x12\x0e\n\x06\x66ormat\x18\x07 \x01(\x05\"B\n*WireInfographicGenerationOptionsProjection\x12\x14\n\x0c\x64\x65tail_level\x18\x05 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notebooklm.internal.android.wire.v1.artifacts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WIRETABLEARTIFACTGENERATIONOPTIONS']._serialized_start=151
  _globals['_WIRETABLEARTIFACTGENERATIONOPTIONS']._serialized_end=240
  _globals['_WIRETABLEARTIFACT']._serialized_start=243
  _globals['_WIRETABLEARTIFACT']._serialized_end=442
  _globals['_WIREARTIFACTTABLEPROJECTION']._serialized_start=444
  _globals['_WIREARTIFACTTABLEPROJECTION']._serialized_end=544
  _globals['_WIREAUDIOOVERVIEWGENERATIONOPTIONSPROJECTION']._serialized_start=546
  _globals['_WIREAUDIOOVERVIEWGENERATIONOPTIONSPROJECTION']._serialized_end=608
  _globals['_WIREINFOGRAPHICGENERATIONOPTIONSPROJECTION']._serialized_start=610
  _globals['_WIREINFOGRAPHICGENERATIONOPTIONSPROJECTION']._serialized_end=676
# @@protoc_insertion_point(module_scope)
