# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notebooklm/internal/android/wire/v1/b2_notebooks.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'notebooklm/internal/android/wire/v1/b2_notebooks.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6notebooklm/internal/android/wire/v1/b2_notebooks.proto\x12#notebooklm.internal.android.wire.v1\"(\n\x18WireCreateProjectRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"0\n\x19WireDeleteProjectsRequest\x12\x13\n\x0bproject_ids\x18\x01 \x03(\t\".\n\x19WireProjectChangeProperty\x12\x11\n\tnew_title\x18\x02 \x01(\t\"n\n\x13WireProjectMutation\x12W\n\x0f\x63hange_property\x18\x04 \x01(\x0b\x32>.notebooklm.internal.android.wire.v1.WireProjectChangeProperty\"{\n\x18WireMutateProjectRequest\x12\x12\n\nproject_id\x18\x01 \x01(\t\x12K\n\tmutations\x18\x02 \x03(\x0b\x32\x38.notebooklm.internal.android.wire.v1.WireProjectMutation\"B\n\x16WireCopyProjectRequest\x12\x19\n\x11source_project_id\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\"6\n WireGenerateNotebookGuideRequest\x12\x12\n\nproject_id\x18\x01 \x01(\t\"+\n\x13WireNotebookSummary\x12\x14\n\x0ctext_summary\x18\x01 \x01(\t\"6\n\x12WireSuggestedTopic\x12\x10\n\x08question\x18\x01 \x01(\t\x12\x0e\n\x06prompt\x18\x02 \x01(\t\"^\n\x13WireSuggestedTopics\x12G\n\x06topics\x18\x01 \x03(\x0b\x32\x37.notebooklm.internal.android.wire.v1.WireSuggestedTopic\"\xb2\x01\n\x11WireNotebookGuide\x12I\n\x07summary\x18\x01 \x01(\x0b\x32\x38.notebooklm.internal.android.wire.v1.WireNotebookSummary\x12R\n\x10suggested_topics\x18\x02 \x01(\x0b\x32\x38.notebooklm.internal.android.wire.v1.WireSuggestedTopics\"s\n!WireGenerateNotebookGuideResponse\x12N\n\x0enotebook_guide\x18\x01 \x01(\x0b\x32\x36.notebooklm.internal.android.wire.v1.WireNotebookGuideb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notebooklm.internal.android.wire.v1.b2_notebooks_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WIRECREATEPROJECTREQUEST']._serialized_start=95
  _globals['_WIRECREATEPROJECTREQUEST']._serialized_end=135
  _globals['_WIREDELETEPROJECTSREQUEST']._serialized_start=137
  _globals['_WIREDELETEPROJECTSREQUEST']._serialized_end=185
  _globals['_WIREPROJECTCHANGEPROPERTY']._serialized_start=187
  _globals['_WIREPROJECTCHANGEPROPERTY']._serialized_end=233
  _globals['_WIREPROJECTMUTATION']._serialized_start=235
  _globals['_WIREPROJECTMUTATION']._serialized_end=345
  _globals['_WIREMUTATEPROJECTREQUEST']._serialized_start=347
  _globals['_WIREMUTATEPROJECTREQUEST']._serialized_end=470
  _globals['_WIRECOPYPROJECTREQUEST']._serialized_start=472
  _globals['_WIRECOPYPROJECTREQUEST']._serialized_end=538
  _globals['_WIREGENERATENOTEBOOKGUIDEREQUEST']._serialized_start=540
  _globals['_WIREGENERATENOTEBOOKGUIDEREQUEST']._serialized_end=594
  _globals['_WIRENOTEBOOKSUMMARY']._serialized_start=596
  _globals['_WIRENOTEBOOKSUMMARY']._serialized_end=639
  _globals['_WIRESUGGESTEDTOPIC']._serialized_start=641
  _globals['_WIRESUGGESTEDTOPIC']._serialized_end=695
  _globals['_WIRESUGGESTEDTOPICS']._serialized_start=697
  _globals['_WIRESUGGESTEDTOPICS']._serialized_end=791
  _globals['_WIRENOTEBOOKGUIDE']._serialized_start=794
  _globals['_WIRENOTEBOOKGUIDE']._serialized_end=972
  _globals['_WIREGENERATENOTEBOOKGUIDERESPONSE']._serialized_start=974
  _globals['_WIREGENERATENOTEBOOKGUIDERESPONSE']._serialized_end=1089
# @@protoc_insertion_point(module_scope)
