# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notebooklm/internal/android/wire/v1/source_content.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'notebooklm/internal/android/wire/v1/source_content.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from notebooklm._android.proto.google.internal.labs.tailwind.orchestration.v1 import chat_pb2 as google_dot_internal_dot_labs_dot_tailwind_dot_orchestration_dot_v1_dot_chat__pb2
from notebooklm._android.proto.google.internal.labs.tailwind.orchestration.v1 import read_pb2 as google_dot_internal_dot_labs_dot_tailwind_dot_orchestration_dot_v1_dot_read__pb2
from notebooklm._android.proto.google.internal.labs.tailwind.orchestration.v1 import sources_pb2 as google_dot_internal_dot_labs_dot_tailwind_dot_orchestration_dot_v1_dot_sources__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8notebooklm/internal/android/wire/v1/source_content.proto\x12#notebooklm.internal.android.wire.v1\x1a\x39google/internal/labs/tailwind/orchestration/v1/chat.proto\x1a\x39google/internal/labs/tailwind/orchestration/v1/read.proto\x1a<google/internal/labs/tailwind/orchestration/v1/sources.proto\"\xa8\x02\n\x16WireLoadSourceResponse\x12\x46\n\x06source\x18\x01 \x01(\x0b\x32\x36.google.internal.labs.tailwind.orchestration.v1.Source\x12Z\n\nplain_text\x18\x02 \x01(\x0b\x32\x46.google.internal.labs.tailwind.orchestration.v1.PlainTextSourceContent\x12\x17\n\x0fmarkdown_string\x18\x03 \x01(\t\x12Q\n\x0ctailwind_doc\x18\x04 \x01(\x0b\x32;.google.internal.labs.tailwind.orchestration.v1.TailwindDocb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notebooklm.internal.android.wire.v1.source_content_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WIRELOADSOURCERESPONSE']._serialized_start=278
  _globals['_WIRELOADSOURCERESPONSE']._serialized_end=574
# @@protoc_insertion_point(module_scope)
