"""Web response codecs that terminate transport grammar at neutral values."""

from .artifacts import decode_artifact, decode_mind_map_artifact, decode_report_suggestion
from .collections import decode_collection
from .documents import decode_structured_document
from .labels import decode_label, decode_label_create_echo, decode_label_list
from .notebooks import (
    decode_notebook,
    decode_notebook_description,
    encode_notebook_guide,
    encode_remove_from_recent,
)
from .notes import decode_created_note, decode_note, decode_notes
from .research import (
    build_report_import_entry,
    build_web_import_entry,
    decode_imported_sources,
    decode_research_start,
    decode_research_tasks,
    encode_research_cancel_params,
    encode_research_import_params,
    encode_research_poll_params,
    encode_research_start_params,
)
from .settings import (
    decode_account_limits,
    decode_get_account_limits,
    decode_get_user_settings,
    decode_set_output_language,
    encode_get_user_settings,
    encode_set_output_language,
)
from .sharing import decode_share_status, decode_shared_user
from .sources import (
    decode_add_source_records,
    decode_file_registration,
    decode_source,
    decode_source_fulltext,
    decode_source_guide,
    decode_source_record,
    decode_source_row,
    decode_source_snapshot,
    encode_add_drive,
    encode_add_text,
    encode_add_url_batch,
    encode_delete,
    encode_get_fulltext,
    encode_get_guide,
    encode_refresh_or_freshness,
    encode_register_file_source,
    encode_source_snapshot,
    encode_update_source,
)
from .studio_documents import (
    decode_generation_status,
    encode_report_generation,
    encode_video_generation,
)
from .suggestions import (
    decode_prompt_suggestions,
    decode_report_suggestions,
    encode_prompt_suggestions,
    encode_report_suggestions,
)

__all__ = [
    "decode_account_limits",
    "decode_created_note",
    "decode_add_source_records",
    "decode_file_registration",
    "decode_generation_status",
    "decode_get_account_limits",
    "decode_get_user_settings",
    "decode_note",
    "decode_notes",
    "decode_artifact",
    "decode_collection",
    "decode_label",
    "decode_label_create_echo",
    "decode_label_list",
    "decode_mind_map_artifact",
    "decode_notebook",
    "decode_notebook_description",
    "decode_prompt_suggestions",
    "decode_report_suggestion",
    "decode_imported_sources",
    "decode_research_start",
    "decode_research_tasks",
    "decode_report_suggestions",
    "decode_set_output_language",
    "decode_share_status",
    "decode_shared_user",
    "decode_source",
    "decode_source_fulltext",
    "decode_source_guide",
    "decode_source_record",
    "decode_source_row",
    "decode_source_snapshot",
    "decode_structured_document",
    "encode_get_user_settings",
    "encode_notebook_guide",
    "encode_prompt_suggestions",
    "encode_report_generation",
    "encode_remove_from_recent",
    "encode_research_cancel_params",
    "encode_research_import_params",
    "encode_research_poll_params",
    "encode_research_start_params",
    "encode_report_suggestions",
    "encode_set_output_language",
    "encode_video_generation",
    "build_report_import_entry",
    "build_web_import_entry",
    "encode_add_drive",
    "encode_add_text",
    "encode_add_url_batch",
    "encode_delete",
    "encode_get_fulltext",
    "encode_get_guide",
    "encode_refresh_or_freshness",
    "encode_register_file_source",
    "encode_source_snapshot",
    "encode_update_source",
]
