# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: google/internal/labs/tailwind/orchestration/v1/account.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'google/internal/labs/tailwind/orchestration/v1/account.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<google/internal/labs/tailwind/orchestration/v1/account.proto\x12.google.internal.labs.tailwind.orchestration.v1\"[\n\x08UserInfo\x12\x14\n\x0c\x61\x63\x63\x65pted_tos\x18\x01 \x01(\x08\x12$\n\x1copted_in_to_marketing_emails\x18\x04 \x01(\x08\x12\x13\n\x0bis_eea_user\x18\t \x01(\x08\"*\n\x0fPremiumUserInfo\x12\x17\n\x0fis_premium_user\x18\x01 \x01(\x08\"\xb2\x01\n\x07\x41\x63\x63ount\x12K\n\tuser_info\x18\x03 \x01(\x0b\x32\x38.google.internal.labs.tailwind.orchestration.v1.UserInfo\x12Z\n\x11premium_user_info\x18\x05 \x01(\x0b\x32?.google.internal.labs.tailwind.orchestration.v1.PremiumUserInfo\"\x1b\n\x19GetOrCreateAccountRequest\"f\n\x1aGetOrCreateAccountResponse\x12H\n\x07\x61\x63\x63ount\x18\x01 \x01(\x0b\x32\x37.google.internal.labs.tailwind.orchestration.v1.Accountb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.internal.labs.tailwind.orchestration.v1.account_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERINFO']._serialized_start=112
  _globals['_USERINFO']._serialized_end=203
  _globals['_PREMIUMUSERINFO']._serialized_start=205
  _globals['_PREMIUMUSERINFO']._serialized_end=247
  _globals['_ACCOUNT']._serialized_start=250
  _globals['_ACCOUNT']._serialized_end=428
  _globals['_GETORCREATEACCOUNTREQUEST']._serialized_start=430
  _globals['_GETORCREATEACCOUNTREQUEST']._serialized_end=457
  _globals['_GETORCREATEACCOUNTRESPONSE']._serialized_start=459
  _globals['_GETORCREATEACCOUNTRESPONSE']._serialized_end=561
# @@protoc_insertion_point(module_scope)
