# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from notebooklm._android.proto.google.internal.labs.tailwind.orchestration.v1 import b1_read_pb2 as google_dot_internal_dot_labs_dot_tailwind_dot_orchestration_dot_v1_dot_b1__read__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in google/internal/labs/tailwind/orchestration/v1/b1_read_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LabsTailwindOrchestrationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetProject = channel.unary_unary(
                '/google.internal.labs.tailwind.orchestration.v1.LabsTailwindOrchestrationService/GetProject',
                request_serializer=google_dot_internal_dot_labs_dot_tailwind_dot_orchestration_dot_v1_dot_b1__read__pb2.GetProjectRequest.SerializeToString,
                response_deserializer=google_dot_internal_dot_labs_dot_tailwind_dot_orchestration_dot_v1_dot_b1__read__pb2.GetProjectResponse.FromString,
                _registered_method=True)
        self.ListRecentlyViewedProjects = channel.unary_unary(
                '/google.internal.labs.tailwind.orchestration.v1.LabsTailwindOrchestrationService/ListRecentlyViewedProjects',
                request_serializer=google_dot_internal_dot_labs_dot_tailwind_dot_orchestration_dot_v1_dot_b1__read__pb2.ListRecentlyViewedProjectsRequest.SerializeToString,
                response_deserializer=google_dot_internal_dot_labs_dot_tailwind_dot_orchestration_dot_v1_dot_b1__read__pb2.ListRecentlyViewedProjectsResponse.FromString,
                _registered_method=True)


class LabsTailwindOrchestrationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRecentlyViewedProjects(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LabsTailwindOrchestrationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetProject': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProject,
                    request_deserializer=google_dot_internal_dot_labs_dot_tailwind_dot_orchestration_dot_v1_dot_b1__read__pb2.GetProjectRequest.FromString,
                    response_serializer=google_dot_internal_dot_labs_dot_tailwind_dot_orchestration_dot_v1_dot_b1__read__pb2.GetProjectResponse.SerializeToString,
            ),
            'ListRecentlyViewedProjects': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRecentlyViewedProjects,
                    request_deserializer=google_dot_internal_dot_labs_dot_tailwind_dot_orchestration_dot_v1_dot_b1__read__pb2.ListRecentlyViewedProjectsRequest.FromString,
                    response_serializer=google_dot_internal_dot_labs_dot_tailwind_dot_orchestration_dot_v1_dot_b1__read__pb2.ListRecentlyViewedProjectsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'google.internal.labs.tailwind.orchestration.v1.LabsTailwindOrchestrationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('google.internal.labs.tailwind.orchestration.v1.LabsTailwindOrchestrationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LabsTailwindOrchestrationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.internal.labs.tailwind.orchestration.v1.LabsTailwindOrchestrationService/GetProject',
            google_dot_internal_dot_labs_dot_tailwind_dot_orchestration_dot_v1_dot_b1__read__pb2.GetProjectRequest.SerializeToString,
            google_dot_internal_dot_labs_dot_tailwind_dot_orchestration_dot_v1_dot_b1__read__pb2.GetProjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRecentlyViewedProjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/google.internal.labs.tailwind.orchestration.v1.LabsTailwindOrchestrationService/ListRecentlyViewedProjects',
            google_dot_internal_dot_labs_dot_tailwind_dot_orchestration_dot_v1_dot_b1__read__pb2.ListRecentlyViewedProjectsRequest.SerializeToString,
            google_dot_internal_dot_labs_dot_tailwind_dot_orchestration_dot_v1_dot_b1__read__pb2.ListRecentlyViewedProjectsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
