# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: google/internal/labs/tailwind/orchestration/v1/notebooks.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'google/internal/labs/tailwind/orchestration/v1/notebooks.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n>google/internal/labs/tailwind/orchestration/v1/notebooks.proto\x12.google.internal.labs.tailwind.orchestration.v1\"$\n\x14\x43reateProjectRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\xaf\x01\n\x0fProjectMutation\x12o\n\x0f\x63hange_property\x18\x04 \x01(\x0b\x32V.google.internal.labs.tailwind.orchestration.v1.ProjectMutation.ChangePropertyMutation\x1a+\n\x16\x43hangePropertyMutation\x12\x11\n\tnew_title\x18\x02 \x01(\t\"~\n\x14MutateProjectRequest\x12\x12\n\nproject_id\x18\x01 \x01(\t\x12R\n\tmutations\x18\x02 \x03(\x0b\x32?.google.internal.labs.tailwind.orchestration.v1.ProjectMutation\",\n\x15\x44\x65leteProjectsRequest\x12\x13\n\x0bproject_ids\x18\x01 \x03(\t\"7\n\x08NextStep\x12\x12\n\nsuggestion\x18\x01 \x01(\t\x12\x17\n\x0fsuggestion_type\x18\x02 \x01(\x05\"c\n\x13NextStepSuggestions\x12L\n\nnext_steps\x18\x01 \x03(\x0b\x32\x38.google.internal.labs.tailwind.orchestration.v1.NextStep\"\'\n\x0fNotebookSummary\x12\x14\n\x0ctext_summary\x18\x01 \x01(\t\"\xc5\x01\n\rNotebookGuide\x12P\n\x07summary\x18\x01 \x01(\x0b\x32?.google.internal.labs.tailwind.orchestration.v1.NotebookSummary\x12\x62\n\x15next_step_suggestions\x18\x06 \x01(\x0b\x32\x43.google.internal.labs.tailwind.orchestration.v1.NextStepSuggestions\"2\n\x1cGenerateNotebookGuideRequest\x12\x12\n\nproject_id\x18\x01 \x01(\t\"v\n\x1dGenerateNotebookGuideResponse\x12U\n\x0enotebook_guide\x18\x01 \x01(\x0b\x32=.google.internal.labs.tailwind.orchestration.v1.NotebookGuideb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.internal.labs.tailwind.orchestration.v1.notebooks_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEPROJECTREQUEST']._serialized_start=114
  _globals['_CREATEPROJECTREQUEST']._serialized_end=150
  _globals['_PROJECTMUTATION']._serialized_start=153
  _globals['_PROJECTMUTATION']._serialized_end=328
  _globals['_PROJECTMUTATION_CHANGEPROPERTYMUTATION']._serialized_start=285
  _globals['_PROJECTMUTATION_CHANGEPROPERTYMUTATION']._serialized_end=328
  _globals['_MUTATEPROJECTREQUEST']._serialized_start=330
  _globals['_MUTATEPROJECTREQUEST']._serialized_end=456
  _globals['_DELETEPROJECTSREQUEST']._serialized_start=458
  _globals['_DELETEPROJECTSREQUEST']._serialized_end=502
  _globals['_NEXTSTEP']._serialized_start=504
  _globals['_NEXTSTEP']._serialized_end=559
  _globals['_NEXTSTEPSUGGESTIONS']._serialized_start=561
  _globals['_NEXTSTEPSUGGESTIONS']._serialized_end=660
  _globals['_NOTEBOOKSUMMARY']._serialized_start=662
  _globals['_NOTEBOOKSUMMARY']._serialized_end=701
  _globals['_NOTEBOOKGUIDE']._serialized_start=704
  _globals['_NOTEBOOKGUIDE']._serialized_end=901
  _globals['_GENERATENOTEBOOKGUIDEREQUEST']._serialized_start=903
  _globals['_GENERATENOTEBOOKGUIDEREQUEST']._serialized_end=953
  _globals['_GENERATENOTEBOOKGUIDERESPONSE']._serialized_start=955
  _globals['_GENERATENOTEBOOKGUIDERESPONSE']._serialized_end=1073
# @@protoc_insertion_point(module_scope)
