# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: google/internal/labs/tailwind/orchestration/v1/organization.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'google/internal/labs/tailwind/orchestration/v1/organization.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from notebooklm._android.proto.google.internal.labs.tailwind.orchestration.v1 import read_pb2 as google_dot_internal_dot_labs_dot_tailwind_dot_orchestration_dot_v1_dot_read__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nAgoogle/internal/labs/tailwind/orchestration/v1/organization.proto\x12.google.internal.labs.tailwind.orchestration.v1\x1a\x39google/internal/labs/tailwind/orchestration/v1/read.proto\"\x8f\x01\n\x0fLabelAndSources\x12\r\n\x05label\x18\x01 \x01(\t\x12L\n\nsource_ids\x18\x02 \x03(\x0b\x32\x38.google.internal.labs.tailwind.orchestration.v1.SourceId\x12\x10\n\x08label_id\x18\x03 \x01(\t\x12\r\n\x05\x65moji\x18\x04 \x01(\t\":\n\x10GetLabelsRequest\x12\x12\n\nproject_id\x18\x02 \x01(\t\x12\x12\n\nlabel_type\x18\x03 \x01(\x05\"\xce\x01\n\x11GetLabelsResponse\x12Z\n\x11label_and_sources\x18\x01 \x03(\x0b\x32?.google.internal.labs.tailwind.orchestration.v1.LabelAndSources\x12]\n\x14notebook_collections\x18\x02 \x03(\x0b\x32?.google.internal.labs.tailwind.orchestration.v1.LabelAndSourcesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.internal.labs.tailwind.orchestration.v1.organization_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LABELANDSOURCES']._serialized_start=177
  _globals['_LABELANDSOURCES']._serialized_end=320
  _globals['_GETLABELSREQUEST']._serialized_start=322
  _globals['_GETLABELSREQUEST']._serialized_end=380
  _globals['_GETLABELSRESPONSE']._serialized_start=383
  _globals['_GETLABELSRESPONSE']._serialized_end=589
# @@protoc_insertion_point(module_scope)
